# -*- coding: utf-8 -*-
"""exp_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14apo8BfcyNUUhBIJs90ZT4UfjL4t4D-T
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = [3, 16, 156, 47, 246, 176, 233, 140, 130, 101, 166, 201, 200, 116, 118, 247, 209,
52, 153, 232, 128, 27,192, 168, 208, 187, 228, 86, 30, 151, 18, 254, 76, 112, 67, 244, 179, 150, 89, 49, 83, 147, 90, 33, 6,158, 80, 35, 186, 127]

N=len(data)

lags=range(35)

autocorr_values=[]

mean_data = np.mean(data)

variance_data = np.var(data)

normalized_data = (data - mean_data) / np.sqrt(variance_data)

for lag in lags:
  if lag == 0:
    autocorr_values.append(1)
  else:
    auto_cov = np.sum((data[:-lag] - mean_data) * (data[lag:] - mean_data)) / N  # Autocovariance
    autocorr_values.append(auto_cov / variance_data)  # Normalize by variance

plt.figure(figsize=(10, 6))
plt.stem(lags, autocorr_values)
plt.title('Autocorrelation of Data')
plt.xlabel('Lag')
plt.ylabel('Autocorrelation')
plt.grid(True)
plt.show()